name: Create and Push Report

on:
  push:
    branches:
      - main

jobs:
  create-and-push-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate report
      run: |
        echo "## Report generated on $(date)" > report.md
        echo "" >> report.md
        
        echo "### Current Branch:" >> report.md
        git branch --show-current >> report.md
        echo "" >> report.md
        
        echo "### Last Commit Message:" >> report.md
        git log -1 --pretty=format:'%s' >> report.md
        echo "" >> report.md
        
        echo "### Number of Files in Repository:" >> report.md
        find . -type f | wc -l >> report.md
        echo "" >> report.md
        
        echo "### Repository Files:" >> report.md
        ls -1 >> report.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --global user.name 'Dinesh-medtech'
        git config --global user.email 'dineshkumar@medtechsoft.co'
        git add report.md
        git commit -m "Add report generated by GitHub Actions"
        git push
