name: Create and Push Report

on:
  push:
    branches:
      - main

jobs:
  create-and-push-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate report
      run: |
        echo "## Report generated on $(date)" > report.md
        echo "" >> report.md
        
        echo "### Current Branch:" >> report.md
        git branch --show-current >> report.md
        echo "" >> report.md
        
        echo "### Last Commit Message:" >> report.md
        git log -1 --pretty=format:'%s' >> report.md
        echo "" >> report.md
        
        echo "### Number of Files in Repository:" >> report.md
        find . -type f | wc -l >> report.md
        echo "" >> report.md
        
        echo "### Repository Files:" >> report.md
        ls -1 >> report.md
            - name: GitHub Push
    # You may pin to the exact commit or the version.
    # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.PAT_TOKEN }}
     
          
    # - name: Commit and push changes
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
    #   run: |
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     git add report.md
    #     git commit -m "Add report generated by GitHub Actions"
    #     git push
