name: Create and Push Report

on:
  push:
    branches:
      - main

jobs:
  create-and-push-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate report
      run: |
        echo "## Report generated on $(date)" > report.md
        echo "" >> report.md
        
        echo "### Current Branch:" >> report.md
        git branch --show-current >> report.md
        echo "" >> report.md
        
        echo "### Last Commit Message:" >> report.md
        git log -1 --pretty=format:'%s' >> report.md
        echo "" >> report.md
        
        echo "### Number of Files in Repository:" >> report.md
        find . -type f | wc -l >> report.md
        echo "" >> report.md
        
        echo "### Repository Files:" >> report.md
        ls -1 >> report.md

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
